language: cpp
branches:
  only:
    - master

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-9
- export CXX="g++-9"

before_script:
  # install google-test
  - sudo apt-get install libgtest-dev
  # install cmake
  - sudo apt-get install cmake 
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo mkdir /usr/local/lib/gtest
  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a

  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - cd $TRAVIS_BUILD_DIR
script:  
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - ./test/tb_main
deploy:
  # to JFROG
  - provider: script
    skip_cleanup: true
    script:
      - curl -H X-JFrog-Art-Api:$JFROG_API_KEY -XPUT "https://cdandrey.jfrog.io/artifactory/otus_game-debian/pool/OtusTankGame;deb.distribution=trusty;deb.component=main;deb.architecture=amd64;" -T OtusTankGame-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
  # to GitHub Releases
  - provider: releases
    tag_name: 0.0.$TRAVIS_BUILD_NUMBER
    target_commitish: $TRAVIS_COMMIT
    api_key: $GITHUB_TOKEN
    file: OtusTankGame-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
    skip_cleanup: true 